# Constants - used by multiple Python files

WINDOW_WIDTH = 600
WINDOW_HEIGHT = 700
GAME_HEIGHT = 560
DIALOG_BOX_OFFSET = 35
DIALOG_BOX_WIDTH = WINDOW_WIDTH - (2 * DIALOG_BOX_OFFSET)

# Scene keys
SCENE_SPLASH = 'scene splash'
SCENE_PLAY = 'scene play'
SCENE_SETTINGS = 'scene settings'

DEFAULT_BUTTON_WIDTH = 100

WHITE = (255, 255, 255)
BLACK = (0, 0, 0)